/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import Controller.WarController;
import java.awt.Color;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author felipe
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private WarController instance;
    private JButton[] botoesEstado;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        instance = WarController.getInstance();
        iniciaComponentesDaTela();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void geraVetorDeBotoes(){
        botoesEstado = new JButton[]{ACRE,ALAGOAS,AMAPA,AMAZONAS,BAHIA,CEARA,DF,ESPIRITOSANTO,
        GOIAS,MARANHAO,MATOGROSSO,MATOGROSSODOSUL,MINASGERAIS,PARA,PARAIBA,PARANA,PERNAMBUCO,
        PIAUI,RIODEJANEIRO,RIOGRANDEDONORTE,RIOGRANDEDOSUL,RONDONIA,RORAIMA,SANTACATARINA,
        SAOPAULO,SERGIPE,TOCANTINS};
    }
    
    private void iniciaComponentesDaTela(){
        
        instance.distribuiEstados();
        
        for (int i = 0; i <instance.getNumeroJogadores(); i++) {
           tabelaJogadores.setValueAt(instance.getNomeJogador(i)+" ("+ instance.getNomeCorJogador(i)+")", i, 0);
           tabelaJogadores.setValueAt(instance.getTotalDeExercitoJogador(i), i, 1);
        }
        geraVetorDeBotoes();
        instance.atualizaMapa(botoesEstado);
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();
        AMAZONAS = new javax.swing.JButton();
        Console = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaJogadores = new javax.swing.JTable();
        Jogando = new javax.swing.JLabel();
        RORAIMA = new javax.swing.JButton();
        MATOGROSSODOSUL = new javax.swing.JButton();
        BAHIA = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Trocar = new javax.swing.JPanel();
        TROCAR = new javax.swing.JButton();
        FINALIZARTRCA = new javax.swing.JButton();
        VALORDATROCA = new javax.swing.JLabel();
        ALOCACAO1 = new javax.swing.JLabel();
        Alocacao = new javax.swing.JPanel();
        FINALIZARALOCAR = new javax.swing.JButton();
        EXERCITORESTANTE = new javax.swing.JLabel();
        ALOCAR = new javax.swing.JButton();
        PARARALOCACAO = new javax.swing.JButton();
        TOTALEXERCITOS = new javax.swing.JLabel();
        ALOCACAO = new javax.swing.JLabel();
        Ataque = new javax.swing.JPanel();
        dado1_vermelho = new javax.swing.JLabel();
        dado2_vermelho = new javax.swing.JLabel();
        dado3_vermelho = new javax.swing.JLabel();
        dado3_amarelo = new javax.swing.JLabel();
        dado2_amarelo = new javax.swing.JLabel();
        PARARATAQUE = new javax.swing.JButton();
        dado1_amarelo = new javax.swing.JLabel();
        FINALIZARATAQUE = new javax.swing.JButton();
        ATACAR = new javax.swing.JButton();
        DADOS = new javax.swing.JButton();
        ATACANTE = new javax.swing.JLabel();
        DEFENSOR = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        ATAQUE = new javax.swing.JLabel();
        Mover = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        N_EXERCITOS_SELECT = new javax.swing.JSpinner();
        N_EXERCITOS = new javax.swing.JLabel();
        finalizar_mover = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        MOVER = new javax.swing.JLabel();
        Cartas = new javax.swing.JPanel();
        FINALIZARTURNO = new javax.swing.JButton();
        CARTA1 = new javax.swing.JButton();
        CARTA2 = new javax.swing.JButton();
        CARTA4 = new javax.swing.JButton();
        CARTA3 = new javax.swing.JButton();
        CARTA5 = new javax.swing.JButton();
        CARTAS = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        MATOGROSSO = new javax.swing.JButton();
        AMAPA = new javax.swing.JButton();
        RONDONIA = new javax.swing.JButton();
        ACRE = new javax.swing.JButton();
        TOCANTINS = new javax.swing.JButton();
        MARANHAO = new javax.swing.JButton();
        PIAUI = new javax.swing.JButton();
        CEARA = new javax.swing.JButton();
        GOIAS = new javax.swing.JButton();
        MINASGERAIS = new javax.swing.JButton();
        SAOPAULO = new javax.swing.JButton();
        PARANA = new javax.swing.JButton();
        ESPIRITOSANTO = new javax.swing.JButton();
        RIODEJANEIRO = new javax.swing.JButton();
        RIOGRANDEDONORTE = new javax.swing.JButton();
        ALAGOAS = new javax.swing.JButton();
        SERGIPE = new javax.swing.JButton();
        RIOGRANDEDOSUL = new javax.swing.JButton();
        SANTACATARINA = new javax.swing.JButton();
        PERNAMBUCO = new javax.swing.JButton();
        PARAIBA = new javax.swing.JButton();
        DF = new javax.swing.JButton();
        PARA = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        OBJETIVO = new javax.swing.JButton();
        FOTODEFUNDO = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WarEs2");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(950, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        console.setColumns(20);
        console.setRows(5);
        console.setText("Início do jogo ~> +01 de exército todos os terrenos\n");
        jScrollPane1.setViewportView(console);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 590, 100));

        AMAZONAS.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        AMAZONAS.setText("1");
        AMAZONAS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(AMAZONAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 40, 20));

        Console.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        Console.setText("Console:");
        jPanel1.add(Console, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 110, 30));

        tabelaJogadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Branco", "22"},
                {"Verde", "17"},
                {"Preto", "7"},
                {" - ", " -"},
                {" - ", " - "},
                {" - ", " -"}
            },
            new String [] {
                "Jogador", "Exécitos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaJogadores.setEnabled(false);
        tabelaJogadores.setRowHeight(17);
        jScrollPane3.setViewportView(tabelaJogadores);
        if (tabelaJogadores.getColumnModel().getColumnCount() > 0) {
            tabelaJogadores.getColumnModel().getColumn(0).setResizable(false);
            tabelaJogadores.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 300, 130));

        Jogando.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jogando.setText("Jogando:");
        jPanel1.add(Jogando, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 130, 30));

        RORAIMA.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        RORAIMA.setText("1");
        RORAIMA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(RORAIMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 40, 20));

        MATOGROSSODOSUL.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        MATOGROSSODOSUL.setText("1");
        MATOGROSSODOSUL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(MATOGROSSODOSUL, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 40, 20));

        BAHIA.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        BAHIA.setText("1");
        BAHIA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(BAHIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 40, 20));

        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jTabbedPane1.setRequestFocusEnabled(false);
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        Trocar.setLayout(null);

        TROCAR.setText("Trocar");
        Trocar.add(TROCAR);
        TROCAR.setBounds(280, 170, 90, 30);

        FINALIZARTRCA.setText("Finalizar");
        FINALIZARTRCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FINALIZARTRCAActionPerformed(evt);
            }
        });
        Trocar.add(FINALIZARTRCA);
        FINALIZARTRCA.setBounds(280, 240, 90, 30);

        VALORDATROCA.setText("Valor da troca: + 10");
        Trocar.add(VALORDATROCA);
        VALORDATROCA.setBounds(20, 220, 160, 40);

        ALOCACAO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Planos de fundo/mar.png"))); // NOI18N
        Trocar.add(ALOCACAO1);
        ALOCACAO1.setBounds(0, 0, 390, 280);

        jTabbedPane1.addTab("Trocar", Trocar);

        Alocacao.setLayout(null);

        FINALIZARALOCAR.setText("Finalizar");
        FINALIZARALOCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FINALIZARALOCARActionPerformed(evt);
            }
        });
        Alocacao.add(FINALIZARALOCAR);
        FINALIZARALOCAR.setBounds(280, 240, 90, 30);

        EXERCITORESTANTE.setText("Exércitos restantes: 5");
        Alocacao.add(EXERCITORESTANTE);
        EXERCITORESTANTE.setBounds(120, 150, 180, 20);

        ALOCAR.setBackground(new java.awt.Color(158, 216, 242));
        ALOCAR.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        ALOCAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Botões/map_pin_fill-48.png"))); // NOI18N
        ALOCAR.setToolTipText("Alocar Exército");
        ALOCAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ALOCAR.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ALOCAR.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        ALOCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALOCARActionPerformed(evt);
            }
        });
        Alocacao.add(ALOCAR);
        ALOCAR.setBounds(80, 70, 60, 50);

        PARARALOCACAO.setBackground(new java.awt.Color(158, 216, 242));
        PARARALOCACAO.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        PARARALOCACAO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Botões/cancelar.png"))); // NOI18N
        PARARALOCACAO.setToolTipText("Remover Exército");
        PARARALOCACAO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PARARALOCACAO.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PARARALOCACAO.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PARARALOCACAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PARARALOCACAOActionPerformed(evt);
            }
        });
        Alocacao.add(PARARALOCACAO);
        PARARALOCACAO.setBounds(210, 70, 60, 50);

        TOTALEXERCITOS.setText("Total de Exércitos: 15");
        Alocacao.add(TOTALEXERCITOS);
        TOTALEXERCITOS.setBounds(120, 10, 160, 17);

        ALOCACAO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Planos de fundo/mar.png"))); // NOI18N
        Alocacao.add(ALOCACAO);
        ALOCACAO.setBounds(0, 0, 390, 280);

        jTabbedPane1.addTab("Alocar", Alocacao);

        Ataque.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Ataque.setLayout(null);

        dado1_vermelho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Dados/anima1v.gif"))); // NOI18N
        Ataque.add(dado1_vermelho);
        dado1_vermelho.setBounds(120, 70, 70, 70);

        dado2_vermelho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Dados/anima2v.gif"))); // NOI18N
        Ataque.add(dado2_vermelho);
        dado2_vermelho.setBounds(190, 70, 70, 70);

        dado3_vermelho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Dados/anima3v.gif"))); // NOI18N
        Ataque.add(dado3_vermelho);
        dado3_vermelho.setBounds(260, 70, 70, 70);

        dado3_amarelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Dados/anima3.gif"))); // NOI18N
        Ataque.add(dado3_amarelo);
        dado3_amarelo.setBounds(260, 150, 80, 70);

        dado2_amarelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Dados/anima2.gif"))); // NOI18N
        Ataque.add(dado2_amarelo);
        dado2_amarelo.setBounds(190, 150, 70, 70);

        PARARATAQUE.setBackground(new java.awt.Color(158, 216, 242));
        PARARATAQUE.setForeground(new java.awt.Color(158, 216, 242));
        PARARATAQUE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Botões/Close3.png"))); // NOI18N
        PARARATAQUE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PARARATAQUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PARARATAQUEActionPerformed(evt);
            }
        });
        Ataque.add(PARARATAQUE);
        PARARATAQUE.setBounds(40, 180, 60, 50);

        dado1_amarelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Dados/anima1.gif"))); // NOI18N
        Ataque.add(dado1_amarelo);
        dado1_amarelo.setBounds(120, 150, 70, 70);

        FINALIZARATAQUE.setText("Finalizar");
        FINALIZARATAQUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FINALIZARATAQUEActionPerformed(evt);
            }
        });
        Ataque.add(FINALIZARATAQUE);
        FINALIZARATAQUE.setBounds(280, 240, 90, 30);

        ATACAR.setBackground(new java.awt.Color(158, 216, 242));
        ATACAR.setForeground(new java.awt.Color(158, 216, 242));
        ATACAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Botões/1411846837_cannon.png"))); // NOI18N
        ATACAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ATACAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATACARActionPerformed(evt);
            }
        });
        Ataque.add(ATACAR);
        ATACAR.setBounds(40, 40, 60, 50);

        DADOS.setBackground(new java.awt.Color(158, 216, 242));
        DADOS.setForeground(new java.awt.Color(158, 216, 242));
        DADOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Botões/dice.png"))); // NOI18N
        DADOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DADOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DADOSActionPerformed(evt);
            }
        });
        Ataque.add(DADOS);
        DADOS.setBounds(40, 110, 60, 50);

        ATACANTE.setText("Rio de janeiro");
        Ataque.add(ATACANTE);
        ATACANTE.setBounds(130, 30, 80, 17);

        DEFENSOR.setText("Minas Gerais");
        Ataque.add(DEFENSOR);
        DEFENSOR.setBounds(270, 30, 90, 17);

        x.setText("X");
        Ataque.add(x);
        x.setBounds(230, 30, 20, 17);

        ATAQUE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Planos de fundo/mar.png"))); // NOI18N
        ATAQUE.setOpaque(true);
        Ataque.add(ATAQUE);
        ATAQUE.setBounds(0, 0, 400, 280);

        jTabbedPane1.addTab("Atacar", Ataque);

        Mover.setLayout(null);

        jButton3.setBackground(new java.awt.Color(158, 216, 242));
        jButton3.setForeground(new java.awt.Color(158, 216, 242));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Botões/go-jump.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Mover.add(jButton3);
        jButton3.setBounds(60, 100, 60, 50);
        Mover.add(N_EXERCITOS_SELECT);
        N_EXERCITOS_SELECT.setBounds(200, 120, 70, 30);

        N_EXERCITOS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        N_EXERCITOS.setText("Número De Exércitos:");
        Mover.add(N_EXERCITOS);
        N_EXERCITOS.setBounds(160, 80, 170, 40);

        finalizar_mover.setText("Finalizar");
        finalizar_mover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizar_moverActionPerformed(evt);
            }
        });
        Mover.add(finalizar_mover);
        finalizar_mover.setBounds(280, 240, 90, 30);

        jButton15.setBackground(new java.awt.Color(158, 216, 242));
        jButton15.setForeground(new java.awt.Color(158, 216, 242));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Botões/icon-map-48.png"))); // NOI18N
        jButton15.setToolTipText("ufuvuk uyf uif ufuyf u uf ");
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        Mover.add(jButton15);
        jButton15.setBounds(60, 30, 60, 50);

        jButton43.setBackground(new java.awt.Color(158, 216, 242));
        jButton43.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Botões/cancelar.png"))); // NOI18N
        jButton43.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton43.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton43.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        Mover.add(jButton43);
        jButton43.setBounds(60, 170, 60, 50);

        MOVER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Planos de fundo/mar.png"))); // NOI18N
        Mover.add(MOVER);
        MOVER.setBounds(0, 0, 400, 280);

        jTabbedPane1.addTab("Mover", Mover);

        Cartas.setLayout(null);

        FINALIZARTURNO.setText("Finalizar Turno");
        FINALIZARTURNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FINALIZARTURNOActionPerformed(evt);
            }
        });
        Cartas.add(FINALIZARTURNO);
        FINALIZARTURNO.setBounds(250, 240, 120, 30);

        CARTA1.setBackground(new java.awt.Color(158, 216, 242));
        CARTA1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        CARTA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Botões/Question-48.png"))); // NOI18N
        CARTA1.setText("CARTA 2");
        CARTA1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CARTA1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        CARTA1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CARTA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARTA1ActionPerformed(evt);
            }
        });
        Cartas.add(CARTA1);
        CARTA1.setBounds(140, 10, 80, 80);

        CARTA2.setBackground(new java.awt.Color(158, 216, 242));
        CARTA2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        CARTA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Botões/Question-48.png"))); // NOI18N
        CARTA2.setText("CARTA 3");
        CARTA2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CARTA2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        CARTA2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CARTA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARTA2ActionPerformed(evt);
            }
        });
        Cartas.add(CARTA2);
        CARTA2.setBounds(260, 10, 80, 80);

        CARTA4.setBackground(new java.awt.Color(158, 216, 242));
        CARTA4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        CARTA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Botões/Question-48.png"))); // NOI18N
        CARTA4.setText("CARTA 4");
        CARTA4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CARTA4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        CARTA4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CARTA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARTA4ActionPerformed(evt);
            }
        });
        Cartas.add(CARTA4);
        CARTA4.setBounds(20, 100, 80, 80);

        CARTA3.setBackground(new java.awt.Color(158, 216, 242));
        CARTA3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        CARTA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Botões/Question-48.png"))); // NOI18N
        CARTA3.setText("CARTA 5");
        CARTA3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CARTA3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        CARTA3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CARTA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARTA3ActionPerformed(evt);
            }
        });
        Cartas.add(CARTA3);
        CARTA3.setBounds(140, 100, 80, 80);

        CARTA5.setBackground(new java.awt.Color(158, 216, 242));
        CARTA5.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        CARTA5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Botões/Question-48.png"))); // NOI18N
        CARTA5.setText("CARTA 1");
        CARTA5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CARTA5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        CARTA5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CARTA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARTA5ActionPerformed(evt);
            }
        });
        Cartas.add(CARTA5);
        CARTA5.setBounds(20, 10, 80, 80);

        CARTAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Planos de fundo/mar.png"))); // NOI18N
        Cartas.add(CARTAS);
        CARTAS.setBounds(0, 0, 390, 280);

        jTabbedPane1.addTab("Cartas", Cartas);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 375, 300));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 378, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1125, 0, 10, 480));

        MATOGROSSO.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        MATOGROSSO.setText("1");
        MATOGROSSO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(MATOGROSSO, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 40, 20));

        AMAPA.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        AMAPA.setText("1");
        AMAPA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(AMAPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 40, 20));

        RONDONIA.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        RONDONIA.setText("1");
        RONDONIA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(RONDONIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 40, 20));

        ACRE.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        ACRE.setText("1");
        ACRE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ACRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 40, 20));

        TOCANTINS.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        TOCANTINS.setText("1");
        TOCANTINS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(TOCANTINS, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 40, 20));

        MARANHAO.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        MARANHAO.setText("1");
        MARANHAO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(MARANHAO, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 40, 20));

        PIAUI.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        PIAUI.setText("1");
        PIAUI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(PIAUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 40, 20));

        CEARA.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        CEARA.setText("1");
        CEARA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(CEARA, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 40, 20));

        GOIAS.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        GOIAS.setText("1");
        GOIAS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(GOIAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 40, 20));

        MINASGERAIS.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        MINASGERAIS.setText("1");
        MINASGERAIS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(MINASGERAIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 40, 20));

        SAOPAULO.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        SAOPAULO.setText("1");
        SAOPAULO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(SAOPAULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 40, 20));

        PARANA.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        PARANA.setText("1");
        PARANA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(PARANA, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 40, 20));

        ESPIRITOSANTO.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        ESPIRITOSANTO.setText("1");
        ESPIRITOSANTO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ESPIRITOSANTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 40, 20));

        RIODEJANEIRO.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        RIODEJANEIRO.setText("1");
        RIODEJANEIRO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RIODEJANEIRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RIODEJANEIROActionPerformed(evt);
            }
        });
        jPanel1.add(RIODEJANEIRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 40, 20));

        RIOGRANDEDONORTE.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        RIOGRANDEDONORTE.setText("1");
        RIOGRANDEDONORTE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(RIOGRANDEDONORTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 40, 20));

        ALAGOAS.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        ALAGOAS.setText("1");
        ALAGOAS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ALAGOAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 40, 20));

        SERGIPE.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        SERGIPE.setText("1");
        SERGIPE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(SERGIPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 40, 20));

        RIOGRANDEDOSUL.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        RIOGRANDEDOSUL.setText("1");
        RIOGRANDEDOSUL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(RIOGRANDEDOSUL, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 40, 20));

        SANTACATARINA.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        SANTACATARINA.setText("1");
        SANTACATARINA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(SANTACATARINA, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 40, 20));

        PERNAMBUCO.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        PERNAMBUCO.setText("1");
        PERNAMBUCO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(PERNAMBUCO, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 40, 20));

        PARAIBA.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        PARAIBA.setText("1");
        PARAIBA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(PARAIBA, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 40, 20));

        DF.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        DF.setText("1");
        DF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(DF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 40, 20));

        PARA.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        PARA.setText("1");
        PARA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(PARA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 40, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 0, 20, 470));

        OBJETIVO.setBackground(new java.awt.Color(158, 216, 242));
        OBJETIVO.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        OBJETIVO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Botões/Question-48.png"))); // NOI18N
        OBJETIVO.setText("Objetivo");
        OBJETIVO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OBJETIVO.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        OBJETIVO.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        OBJETIVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OBJETIVOActionPerformed(evt);
            }
        });
        jPanel1.add(OBJETIVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 80, 80));

        FOTODEFUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Planos de fundo/mapa.jpg"))); // NOI18N
        jPanel1.add(FOTODEFUNDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 580));

        jMenu1.setText("Arquivo");

        jMenuItem2.setText("Novo Jogo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");

        jMenuItem1.setText("Regras");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem3.setText("Créditos");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void PARARATAQUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PARARATAQUEActionPerformed
        int numDado = new Random().nextInt(6);
        tabelaJogadores.setRowSelectionInterval(numDado,numDado);
        tabelaJogadores.setSelectionBackground(Color.RED);
        
    }//GEN-LAST:event_PARARATAQUEActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void FINALIZARALOCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FINALIZARALOCARActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setEnabledAt(0, false);
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setSelectedIndex(1);
        jTabbedPane1.setEnabledAt(2, false);
    }//GEN-LAST:event_FINALIZARALOCARActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void FINALIZARATAQUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FINALIZARATAQUEActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setEnabledAt(0, false);
        jTabbedPane1.setEnabledAt(2, true);
        jTabbedPane1.setSelectedIndex(2);
        jTabbedPane1.setEnabledAt(1, false);
    }//GEN-LAST:event_FINALIZARATAQUEActionPerformed

    private void finalizar_moverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizar_moverActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setEnabledAt(0, false);
        jTabbedPane1.setSelectedIndex(3);
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
    }//GEN-LAST:event_finalizar_moverActionPerformed

    private void FINALIZARTURNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FINALIZARTURNOActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(0, true);
        jTabbedPane1.setSelectedIndex(0);
        jTabbedPane1.setEnabledAt(2, false);
    }//GEN-LAST:event_FINALIZARTURNOActionPerformed

    private void OBJETIVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OBJETIVOActionPerformed
        // TODO add your handling code here:
        String a = "/view/imagens/Cartas Objetivo/con_nordeste_centrooeste.jpg";
        JOptionPane.showMessageDialog(this, null, "Objetivo", 2,new javax.swing.ImageIcon(getClass().getResource(a)));
    }//GEN-LAST:event_OBJETIVOActionPerformed

    private void ATACARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATACARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ATACARActionPerformed

    private void DADOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DADOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DADOSActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new TelaInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void ALOCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALOCARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALOCARActionPerformed

    private void PARARALOCACAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PARARALOCACAOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PARARALOCACAOActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton43ActionPerformed

    private void RIODEJANEIROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RIODEJANEIROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RIODEJANEIROActionPerformed

    private void FINALIZARTRCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FINALIZARTRCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FINALIZARTRCAActionPerformed

    private void CARTA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARTA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CARTA1ActionPerformed

    private void CARTA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARTA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CARTA2ActionPerformed

    private void CARTA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARTA4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CARTA4ActionPerformed

    private void CARTA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARTA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CARTA3ActionPerformed

    private void CARTA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARTA5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CARTA5ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACRE;
    private javax.swing.JButton ALAGOAS;
    private javax.swing.JLabel ALOCACAO;
    private javax.swing.JLabel ALOCACAO1;
    private javax.swing.JButton ALOCAR;
    private javax.swing.JButton AMAPA;
    private javax.swing.JButton AMAZONAS;
    private javax.swing.JLabel ATACANTE;
    private javax.swing.JButton ATACAR;
    private javax.swing.JLabel ATAQUE;
    private javax.swing.JPanel Alocacao;
    private javax.swing.JPanel Ataque;
    private javax.swing.JButton BAHIA;
    private javax.swing.JButton CARTA1;
    private javax.swing.JButton CARTA2;
    private javax.swing.JButton CARTA3;
    private javax.swing.JButton CARTA4;
    private javax.swing.JButton CARTA5;
    private javax.swing.JLabel CARTAS;
    private javax.swing.JButton CEARA;
    private javax.swing.JPanel Cartas;
    private javax.swing.JLabel Console;
    private javax.swing.JButton DADOS;
    private javax.swing.JLabel DEFENSOR;
    private javax.swing.JButton DF;
    private javax.swing.JButton ESPIRITOSANTO;
    private javax.swing.JLabel EXERCITORESTANTE;
    private javax.swing.JButton FINALIZARALOCAR;
    private javax.swing.JButton FINALIZARATAQUE;
    private javax.swing.JButton FINALIZARTRCA;
    private javax.swing.JButton FINALIZARTURNO;
    private javax.swing.JLabel FOTODEFUNDO;
    private javax.swing.JButton GOIAS;
    private javax.swing.JLabel Jogando;
    private javax.swing.JButton MARANHAO;
    private javax.swing.JButton MATOGROSSO;
    private javax.swing.JButton MATOGROSSODOSUL;
    private javax.swing.JButton MINASGERAIS;
    private javax.swing.JLabel MOVER;
    private javax.swing.JPanel Mover;
    private javax.swing.JLabel N_EXERCITOS;
    private javax.swing.JSpinner N_EXERCITOS_SELECT;
    private javax.swing.JButton OBJETIVO;
    private javax.swing.JButton PARA;
    private javax.swing.JButton PARAIBA;
    private javax.swing.JButton PARANA;
    private javax.swing.JButton PARARALOCACAO;
    private javax.swing.JButton PARARATAQUE;
    private javax.swing.JButton PERNAMBUCO;
    private javax.swing.JButton PIAUI;
    private javax.swing.JButton RIODEJANEIRO;
    private javax.swing.JButton RIOGRANDEDONORTE;
    private javax.swing.JButton RIOGRANDEDOSUL;
    private javax.swing.JButton RONDONIA;
    private javax.swing.JButton RORAIMA;
    private javax.swing.JButton SANTACATARINA;
    private javax.swing.JButton SAOPAULO;
    private javax.swing.JButton SERGIPE;
    private javax.swing.JButton TOCANTINS;
    private javax.swing.JLabel TOTALEXERCITOS;
    private javax.swing.JButton TROCAR;
    private javax.swing.JPanel Trocar;
    private javax.swing.JLabel VALORDATROCA;
    private javax.swing.JTextArea console;
    private javax.swing.JLabel dado1_amarelo;
    private javax.swing.JLabel dado1_vermelho;
    private javax.swing.JLabel dado2_amarelo;
    private javax.swing.JLabel dado2_vermelho;
    private javax.swing.JLabel dado3_amarelo;
    private javax.swing.JLabel dado3_vermelho;
    private javax.swing.JButton finalizar_mover;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton43;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabelaJogadores;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
